name: "Integration Tests"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  models: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GOPROXY: https://proxy.golang.org/,direct
      GOPRIVATE: ""
      GONOPROXY: ""
      GONOSUMDB: github.com/github/*
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run integration tests
        run: make integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}